export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';

export const SAVE_PRODUCTS_SUCCESS = 'SAVE_PRODUCTS_SUCCESS';

export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';

export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
