export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";

export const SAVE_PRODUCTS_SUCCESS = "SAVE_PRODUCTS_SUCCESS";

export const PRODUCTS_LOADING = "PRODUCTS_LOADING";

export const PRODUCTS_ERROR = "PRODUCTS_ERROR";

export const NOTES_LOADING = "NOTES_LOADING";

export const NOTES_ERROR = "NOTES_ERROR";

export const NOTES_LOADED = "NOTES_LOADED";

export const NOTE_SAVED = "NOTE_SAVED";

export const NOTE_DELETED = "NOTE_DELETED";

export const NOTE_UPDATED = "NOTE_UPDATED";
